import "./globals.css";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const fontDisplay = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-display",
});

const fontBody = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="text-base text-[#667B79] md:text-lg">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
