import "./globals.css";
import {
  Inter as FontBody,
  Plus_Jakarta_Sans as FontDisplay,
} from "next/font/google";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const fontDisplay = FontDisplay({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-display",
});

const fontBody = FontBody({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-body",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="text-base text-[#667B79] md:text-lg">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
